// lfl_actions_def.h - by Sergey 'iOrange' Kudlay <programmist.c@gmail.com> 2010

// SWF actions opcodes

#ifndef	__lfl_actions_def_h__
#define	__lfl_actions_def_h__

enum E_SWF_ACTIONS
{
	ACTION_EndOfActions					= 0x00,
	ACTION_NextFrame					= 0x04,
	ACTION_PrevFrame					= 0x05,
	ACTION_ActionPlay					= 0x06,
	ACTION_ActionStop					= 0x07,
	ACTION_ToggleQuality				= 0x08,
	ACTION_StopSounds					= 0x09,
	ACTION_Add							= 0x0A,
	ACTION_Sub							= 0x0B,
	ACTION_Multiply						= 0x0C,
	ACTION_Divide						= 0x0D,
	ACTION_Equal						= 0x0E,
	ACTION_LessThan						= 0x0F,
	ACTION_LogicalAnd					= 0x10,
	ACTION_LogicalOr					= 0x11,
	ACTION_LogicalNot					= 0x12,
	ACTION_StringEqual					= 0x13,
	ACTION_StringLength					= 0x14,
	ACTION_SubString					= 0x15,
	ACTION_Pop							= 0x17,
	ACTION_Int							= 0x18,
	ACTION_GetVariable					= 0x1C,
	ACTION_SetVariable					= 0x1D,
	ACTION_SetTarget					= 0x20,
	ACTION_StringConcat					= 0x21,
	ACTION_GetProperty					= 0x22,
	ACTION_SetProperty					= 0x23,
	ACTION_DuplicateMovieClip			= 0x24,
	ACTION_RemoveMovieClip				= 0x25,
	ACTION_Trace						= 0x26,
	ACTION_StartDragMovieClip			= 0x27,
	ACTION_StopDragMovieClip			= 0x28,
	ACTION_StringLessThan				= 0x29,
	ACTION_Throw						= 0x2A,
	ACTION_CastObject					= 0x2B,
	ACTION_Implements					= 0x2C,
	ACTION_Random						= 0x30,
	ACTION_MBStringLength				= 0x31,
	ACTION_CharToAscii					= 0x32,		// ASCII code of first character
	ACTION_AsciiToChar					= 0x33,
	ACTION_GetTimer						= 0x34,
	ACTION_MBSubString					= 0x35,
	ACTION_MBCharToAscii				= 0x36,
	ACTION_MBAsciiToChar				= 0x37,
	ACTION_Delete						= 0x3A,
	ACTION_Delete2						= 0x3B,
	ACTION_SetLocal						= 0x3C,
	ACTION_CallFunction					= 0x3D,
	ACTION_Return						= 0x3E,
	ACTION_Modulo						= 0x3F,
	ACTION_New							= 0x40,
	ACTION_DeclareLocal					= 0x41,
	ACTION_InitArray					= 0x42,
	ACTION_DeclareObject				= 0x43,
	ACTION_TypeOf						= 0x44,
	ACTION_GetTarget					= 0x45,
	ACTION_Enumerate					= 0x46,
	ACTION_Add_Typed					= 0x47,
	ACTION_LessThan_Typed				= 0x48,
	ACTION_Equal_Typed					= 0x49,
	ACTION_ToNumber						= 0x4A,
	ACTION_ToString						= 0x4B,
	ACTION_Duplicate					= 0x4C,
	ACTION_Swap							= 0x4D,
	ACTION_GetMember					= 0x4E,
	ACTION_SetMember					= 0x4F,
	ACTION_Increment					= 0x50,
	ACTION_Decrement					= 0x51,
	ACTION_CallMethod					= 0x52,
	ACTION_NewMethod					= 0x53,
	ACTION_InstanceOf					= 0x54,
	ACTION_EnumerateObject				= 0x55,
	ACTION_BitwiseAnd					= 0x60,
	ACTION_BitwiseOr					= 0x61,
	ACTION_BitwiseXor					= 0x62,
	ACTION_BitwiseShiftLeft				= 0x63,
	ACTION_BitwiseShiftRight_signed		= 0x64,
	ACTION_BitwiseShiftRight_unsigned	= 0x65,
	ACTION_StrictEqual					= 0x66,
	ACTION_GreaterThan_Typed			= 0x67,
	ACTION_StringGreaterThan			= 0x68,
	ACTION_Extends						= 0x69,

	Last_SWF_Action
};

#endif	// __lfl_actions_def_h__
